using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace EADWebApplication.Models
{
    public class Category
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }  // Auto-generated by MongoDB

        public string CategoryName { get; set; }
    }
}
